default_install_hook_types: [pre-commit, pre-push, post-commit]

repos:
  - repo: local
    hooks:
      - id: pytest
        name: Executar testes
        entry: uv run pytest
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]

      - id: protected-branches
        name: Proteger branches main e rc
        entry: uv run python hooks/pre-push
        language: system
        pass_filenames: false
        always_run: true
        verbose: true
        stages: [pre-push]

      - id: commit-summary
        name: Mostrar resumo do commit
        entry: bash hooks/post-commit
        language: system
        pass_filenames: false
        always_run: true
        verbose: true
        stages: [post-commit]